#!/usr/bin/env python3
"""Phase 1 of the Freetown house - the spreadsheet, brought in whole.

96 lines, every one of them real: what was agreed, what went out as a
deposit, what went out at the end, and what is still owed. The totals were
checked against the sheet's own figures before any of this was written -
649,860 agreed, 578,760 paid, 71,100 outstanding. They match to the leone.

The people are separated from the things. The welder, the electrician, the
plumber and the rest are people with accounts; cement, tiles and the fridge
are things that were bought. The first carpenter is kept apart from the one
who came after him, because he is still owed 6,750 and that should not get
lost behind his replacement.

Nothing from the first two houses is in here. Tracking started with the
third building, and that is what Phase 1 is.

Run once from the src folder with:  python3 import_phase1.py
"""
import sqlite3, os, sys

DB = os.getenv("AMI_DB_PATH", "data/ami_memory.db")
WHEN = "2026-05-17"          # the sheet's own date - no per-line dates in it
CUR = "SLE"

ROWS = [{'who': 'Welder',
  'person': 'The welder',
  'trade': 'welder',
  'what': 'Welder',
  'agreed': 14000.0,
  'deposit': 0.0,
  'final': 14000.0},
 {'who': 'Welder',
  'person': 'The welder',
  'trade': 'welder',
  'what': 'Pan',
  'agreed': 8000.0,
  'deposit': 0.0,
  'final': 8000.0},
 {'who': 'Welder',
  'person': 'The welder',
  'trade': 'welder',
  'what': 'Workmanship (pan + rails) + Storage door',
  'agreed': 8100.0,
  'deposit': 0.0,
  'final': 8100.0},
 {'who': 'Carpenter (the first guy)',
  'person': 'The first carpenter',
  'trade': 'carpenter',
  'what': 'Carpentry work',
  'agreed': 20000.0,
  'deposit': 13250.0,
  'final': 0.0},
 {'who': 'Sliding Door',
  'person': None,
  'trade': '',
  'what': 'Sliding door supply/install + net',
  'agreed': 25000.0,
  'deposit': 20000.0,
  'final': 0.0},
 {'who': 'Windows',
  'person': None,
  'trade': '',
  'what': 'Window supply/install',
  'agreed': 37000.0,
  'deposit': 37000.0,
  'final': 0.0},
 {'who': 'Door',
  'person': None,
  'trade': '',
  'what': 'Main entrance door',
  'agreed': 6000.0,
  'deposit': 6000.0,
  'final': 0.0},
 {'who': 'Blinds',
  'person': None,
  'trade': '',
  'what': 'Living/bedroom blinds',
  'agreed': 2000.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Electrician',
  'person': 'The electrician',
  'trade': 'electrician',
  'what': 'Electrical materials',
  'agreed': 23500.0,
  'deposit': 21690.0,
  'final': 0.0},
 {'who': 'Electrician',
  'person': 'The electrician',
  'trade': 'electrician',
  'what': 'Workmanship',
  'agreed': 5000.0,
  'deposit': 4050.0,
  'final': 0.0},
 {'who': 'AC',
  'person': None,
  'trade': '',
  'what': 'AC installation workmanship',
  'agreed': 400.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Toilet 1',
  'person': None,
  'trade': '',
  'what': 'First toilet unit',
  'agreed': 7000.0,
  'deposit': 7000.0,
  'final': 0.0},
 {'who': 'Toilet 2',
  'person': None,
  'trade': '',
  'what': 'Second toilet unit',
  'agreed': 4000.0,
  'deposit': 4000.0,
  'final': 0.0},
 {'who': 'Plumber',
  'person': 'The plumber',
  'trade': 'plumber',
  'what': 'Plumbing workmanship',
  'agreed': 3000.0,
  'deposit': 2020.0,
  'final': 980.0},
 {'who': 'Gas Cooker',
  'person': None,
  'trade': '',
  'what': 'Gas cooker unit',
  'agreed': 11100.0,
  'deposit': 0.0,
  'final': 11100.0},
 {'who': 'Gas Bottles',
  'person': None,
  'trade': '',
  'what': '3 bottles + gas + tubes',
  'agreed': 4000.0,
  'deposit': 0.0,
  'final': 4000.0},
 {'who': 'Alie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'Work 1',
  'agreed': 12000.0,
  'deposit': 7000.0,
  'final': 0.0},
 {'who': 'Umu',
  'person': 'Umu',
  'trade': 'labour',
  'what': 'Labour / services',
  'agreed': 10100.0,
  'deposit': 0.0,
  'final': 10100.0},
 {'who': 'Compound',
  'person': None,
  'trade': '',
  'what': 'Cleaning + spraying of compound/yard',
  'agreed': 5000.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Cement',
  'person': None,
  'trade': '',
  'what': 'Cement supply',
  'agreed': 11500.0,
  'deposit': 0.0,
  'final': 11500.0},
 {'who': 'Center Table',
  'person': None,
  'trade': '',
  'what': 'Center table',
  'agreed': 4000.0,
  'deposit': 0.0,
  'final': 4000.0},
 {'who': 'TBD',
  'person': None,
  'trade': '',
  'what': 'oil (gallon)',
  'agreed': 200.0,
  'deposit': 0.0,
  'final': 200.0},
 {'who': 'TBD',
  'person': None,
  'trade': '',
  'what': 'Box nails',
  'agreed': 650.0,
  'deposit': 0.0,
  'final': 650.0},
 {'who': 'TBD',
  'person': None,
  'trade': '',
  'what': 'Stick',
  'agreed': 1250.0,
  'deposit': 0.0,
  'final': 1250.0},
 {'who': 'TBD',
  'person': None,
  'trade': '',
  'what': 'Sand',
  'agreed': 5500.0,
  'deposit': 0.0,
  'final': 5500.0},
 {'who': 'Pillows',
  'person': None,
  'trade': '',
  'what': '8 Pillows',
  'agreed': 1200.0,
  'deposit': 0.0,
  'final': 1200.0},
 {'who': 'Chandelier Lights',
  'person': None,
  'trade': '',
  'what': 'Lighting for 2 kitchens (placeholder)',
  'agreed': 5000.0,
  'deposit': 0.0,
  'final': 5000.0},
 {'who': 'Security Camera',
  'person': None,
  'trade': '',
  'what': 'Camera installation (assumed)',
  'agreed': 3500.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Locks',
  'person': None,
  'trade': '',
  'what': 'Smart lock + security locks (assumed)',
  'agreed': 3500.0,
  'deposit': 0.0,
  'final': 2800.0},
 {'who': 'Kitchen Blinds',
  'person': None,
  'trade': '',
  'what': 'Blinds for 2 kitchens',
  'agreed': 3600.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Trash Collection',
  'person': None,
  'trade': '',
  'what': 'Collect all trash from site',
  'agreed': 6400.0,
  'deposit': 6400.0,
  'final': 0.0},
 {'who': 'House Cleaning',
  'person': None,
  'trade': '',
  'what': 'Kai + 2 friends — clean the house',
  'agreed': 2000.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Car Registration',
  'person': None,
  'trade': '',
  'what': 'Car Registration',
  'agreed': 7000.0,
  'deposit': 0.0,
  'final': 7000.0},
 {'who': 'Plumber',
  'person': 'The plumber',
  'trade': 'plumber',
  'what': 'Plumber asked Ami for this',
  'agreed': 300.0,
  'deposit': 0.0,
  'final': 300.0},
 {'who': 'Plastic bag',
  'person': None,
  'trade': '',
  'what': 'plastic box',
  'agreed': 2000.0,
  'deposit': 0.0,
  'final': 2000.0},
 {'who': 'Orange charges',
  'person': None,
  'trade': '',
  'what': 'charges for money sent',
  'agreed': 2000.0,
  'deposit': 0.0,
  'final': 2000.0},
 {'who': 'Money to Ami',
  'person': None,
  'trade': '',
  'what': 'Asked Ami to take money',
  'agreed': 1300.0,
  'deposit': 0.0,
  'final': 1300.0},
 {'who': 'ceiling',
  'person': None,
  'trade': '',
  'what': 'Gypsum Boards',
  'agreed': 33600.0,
  'deposit': 0.0,
  'final': 33600.0},
 {'who': 'Workmanship - Ceiling',
  'person': 'The ceiling guy',
  'trade': 'ceiling',
  'what': 'For the Gypsum boards (worksmanship)',
  'agreed': 11060.0,
  'deposit': 11060.0,
  'final': 0.0},
 {'who': 'Workmanship (Stone Guy)',
  'person': 'The stone guy',
  'trade': 'stonework',
  'what': 'Workmanship (Stone Guy)',
  'agreed': 500.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'To Mr Allie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'To cover the hole in the bedroom',
  'agreed': 2780.0,
  'deposit': 0.0,
  'final': 2780.0},
 {'who': 'Materials for ceiling',
  'person': None,
  'trade': '',
  'what': 'Omega (or something like that)',
  'agreed': 3350.0,
  'deposit': 0.0,
  'final': 3350.0},
 {'who': 'Ceiling Guy',
  'person': 'The ceiling guy',
  'trade': 'ceiling',
  'what': 'Transportation',
  'agreed': 120.0,
  'deposit': 0.0,
  'final': 120.0},
 {'who': 'Water heater',
  'person': None,
  'trade': '',
  'what': 'Water heater',
  'agreed': 3000.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Umo',
  'person': 'Umo',
  'trade': 'supplier',
  'what': 'Ceiling Boards (extra 12)',
  'agreed': 4500.0,
  'deposit': 0.0,
  'final': 4500.0},
 {'who': 'Kai',
  'person': 'Kai',
  'trade': '',
  'what': 'Taxi money to go get the water heater',
  'agreed': 120.0,
  'deposit': 0.0,
  'final': 120.0},
 {'who': 'AC',
  'person': None,
  'trade': '',
  'what': 'For 3rd house',
  'agreed': 4000.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Tile Man',
  'person': 'The tile man',
  'trade': 'tiling',
  'what': 'Workmanship to Tile the entire house',
  'agreed': 15000.0,
  'deposit': 15000.0,
  'final': 0.0},
 {'who': 'Mastic estimate',
  'person': None,
  'trade': '',
  'what': 'Mastic, shine paper, etc…',
  'agreed': 21720.0,
  'deposit': 0.0,
  'final': 21720.0},
 {'who': 'Mastic Workmanship',
  'person': 'The mastic guy',
  'trade': 'paint and mastic',
  'what': 'Workmanship for paint and mastic',
  'agreed': 35000.0,
  'deposit': 18110.0,
  'final': 0.0},
 {'who': 'Tiles',
  'person': None,
  'trade': '',
  'what': 'Tiles for the entire project',
  'agreed': 37490.0,
  'deposit': 0.0,
  'final': 37490.0},
 {'who': 'Meter',
  'person': None,
  'trade': '',
  'what': 'Phase 3 meter',
  'agreed': 3800.0,
  'deposit': 0.0,
  'final': 3800.0},
 {'who': 'bathroom doors',
  'person': None,
  'trade': '',
  'what': 'X 2 doors',
  'agreed': 3000.0,
  'deposit': 0.0,
  'final': 3000.0},
 {'who': 'Paint',
  'person': None,
  'trade': '',
  'what': 'Paint for the entire house (X3)',
  'agreed': 12000.0,
  'deposit': 0.0,
  'final': 12000.0},
 {'who': 'Umo',
  'person': 'Umo',
  'trade': 'supplier',
  'what': 'materials for Mr Allie (cements, PVC, etc)',
  'agreed': 14050.0,
  'deposit': 0.0,
  'final': 14050.0},
 {'who': "Ami's mom",
  'person': "Aminata's mother",
  'trade': '',
  'what': 'For her electricity',
  'agreed': 2000.0,
  'deposit': 0.0,
  'final': 2000.0},
 {'who': 'For Mr Allie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'materials for the kitchen for Ami',
  'agreed': 1450.0,
  'deposit': 0.0,
  'final': 1450.0},
 {'who': 'electrician',
  'person': 'The electrician',
  'trade': 'electrician',
  'what': 'for the washer machine',
  'agreed': 2800.0,
  'deposit': 0.0,
  'final': 2800.0},
 {'who': 'plumber',
  'person': 'The plumber',
  'trade': 'plumber',
  'what': 'for his work with the water heater',
  'agreed': 555.0,
  'deposit': 0.0,
  'final': 555.0},
 {'who': 'Plumber',
  'person': 'The plumber',
  'trade': 'plumber',
  'what': 'For the extra work for the bathroom',
  'agreed': 1350.0,
  'deposit': 0.0,
  'final': 1350.0},
 {'who': 'Plumber',
  'person': 'The plumber',
  'trade': 'plumber',
  'what': 'Work for the bathroom (3rd place)',
  'agreed': 1210.0,
  'deposit': 0.0,
  'final': 1210.0},
 {'who': 'carpenter',
  'person': 'The carpenter',
  'trade': 'carpenter',
  'what': 'for the new work',
  'agreed': 34500.0,
  'deposit': 34500.0,
  'final': 0.0},
 {'who': 'Mr Allie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'Kitchen (3rd Place)',
  'agreed': 2000.0,
  'deposit': 0.0,
  'final': 2000.0},
 {'who': 'Marble',
  'person': None,
  'trade': '',
  'what': 'from Dija',
  'agreed': 7000.0,
  'deposit': 0.0,
  'final': 7000.0},
 {'who': 'carpenter',
  'person': 'The carpenter',
  'trade': 'carpenter',
  'what': 'for transportation of chair',
  'agreed': 1000.0,
  'deposit': 0.0,
  'final': 1000.0},
 {'who': 'door',
  'person': None,
  'trade': '',
  'what': 'Welder',
  'agreed': 1500.0,
  'deposit': 0.0,
  'final': 1500.0},
 {'who': 'Tile',
  'person': None,
  'trade': '',
  'what': 'Tile',
  'agreed': 1000.0,
  'deposit': 0.0,
  'final': 1000.0},
 {'who': 'money for bucket',
  'person': None,
  'trade': '',
  'what': 'money for bucket',
  'agreed': 310.0,
  'deposit': 0.0,
  'final': 310.0},
 {'who': 'Umo',
  'person': 'Umo',
  'trade': 'supplier',
  'what': 'Umo',
  'agreed': 16300.0,
  'deposit': 16300.0,
  'final': 0.0},
 {'who': 'Umo',
  'person': 'Umo',
  'trade': 'supplier',
  'what': 'Umo',
  'agreed': 11700.0,
  'deposit': 0.0,
  'final': 11700.0},
 {'who': 'Electrician',
  'person': 'The electrician',
  'trade': 'electrician',
  'what': 'for the step lights',
  'agreed': 3120.0,
  'deposit': 0.0,
  'final': 3120.0},
 {'who': 'mr Allie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'for sticks and nails',
  'agreed': 1190.0,
  'deposit': 0.0,
  'final': 1190.0},
 {'who': 'Ami',
  'person': 'Aminata',
  'trade': 'runs the site',
  'what': 'for food',
  'agreed': 1000.0,
  'deposit': 0.0,
  'final': 1000.0},
 {'who': 'Dija',
  'person': 'Dija',
  'trade': 'supplier',
  'what': 'Sink + Mable (- the black toilette)',
  'agreed': 4500.0,
  'deposit': 0.0,
  'final': 4500.0},
 {'who': 'Tiles',
  'person': None,
  'trade': '',
  'what': 'Extra',
  'agreed': 5190.0,
  'deposit': 0.0,
  'final': 5190.0},
 {'who': 'Airport Transportation',
  'person': None,
  'trade': '',
  'what': 'for the water dispenser and rugs',
  'agreed': 400.0,
  'deposit': 0.0,
  'final': 400.0},
 {'who': 'Kitchen Guy',
  'person': 'Ahmed, the kitchen guy',
  'trade': 'kitchen fitter',
  'what': 'Ahmed for the mable',
  'agreed': 2500.0,
  'deposit': 2500.0,
  'final': 0.0},
 {'who': 'Etsa',
  'person': 'Etsa',
  'trade': '',
  'what': 'Meter Card (X 2)',
  'agreed': 300.0,
  'deposit': 0.0,
  'final': 300.0},
 {'who': 'Jeremiah',
  'person': 'Jeremiah Muhea Squire',
  'trade': 'GII Bo Hub',
  'what': 'For naming of their baby',
  'agreed': 1000.0,
  'deposit': 0.0,
  'final': 1000.0},
 {'who': 'Umu',
  'person': 'Umu',
  'trade': 'labour',
  'what': 'For Cememnt, 3 paints + nails',
  'agreed': 8410.0,
  'deposit': 0.0,
  'final': 8410.0},
 {'who': "Kai's birthday",
  'person': None,
  'trade': '',
  'what': "Kai's birthday",
  'agreed': 300.0,
  'deposit': 0.0,
  'final': 300.0},
 {'who': 'Jeremiah',
  'person': 'Jeremiah Muhea Squire',
  'trade': 'GII Bo Hub',
  'what': 'For Center (Bo)',
  'agreed': 5000.0,
  'deposit': 0.0,
  'final': 5000.0},
 {'who': 'Mr Allie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'Cement',
  'agreed': 1200.0,
  'deposit': 0.0,
  'final': 1200.0},
 {'who': 'Plumber',
  'person': 'The plumber',
  'trade': 'plumber',
  'what': 'Water Guard + Pipes + Transport',
  'agreed': 5100.0,
  'deposit': 0.0,
  'final': 5100.0},
 {'who': 'Electrician',
  'person': 'The electrician',
  'trade': 'electrician',
  'what': 'for cables, sockets, pipes and breakers',
  'agreed': 10150.0,
  'deposit': 0.0,
  'final': 10150.0},
 {'who': 'Julie',
  'person': 'Julie',
  'trade': '',
  'what': 'for the baby',
  'agreed': 1500.0,
  'deposit': 0.0,
  'final': 1500.0},
 {'who': 'Refrigerator',
  'person': None,
  'trade': '',
  'what': 'Refrigerator',
  'agreed': 10000.0,
  'deposit': 0.0,
  'final': 0.0},
 {'who': 'Carpenter',
  'person': 'The carpenter',
  'trade': 'carpenter',
  'what': 'For transporting the couches',
  'agreed': 1000.0,
  'deposit': 0.0,
  'final': 1000.0},
 {'who': 'door lock',
  'person': None,
  'trade': '',
  'what': 'door lock',
  'agreed': 1820.0,
  'deposit': 0.0,
  'final': 1820.0},
 {'who': 'Umo',
  'person': 'Umo',
  'trade': 'supplier',
  'what': 'Umo',
  'agreed': 15345.0,
  'deposit': 0.0,
  'final': 15345.0},
 {'who': 'Keke',
  'person': None,
  'trade': '',
  'what': 'Keke',
  'agreed': 500.0,
  'deposit': 0.0,
  'final': 500.0},
 {'who': 'Transportation',
  'person': None,
  'trade': '',
  'what': "Shipment from China (Marie's)",
  'agreed': 5100.0,
  'deposit': 0.0,
  'final': 5100.0},
 {'who': 'Mr Allie',
  'person': 'Mr Allie',
  'trade': 'builder',
  'what': 'stick and for the water leakage + PVC + Gutter Tie',
  'agreed': 3820.0,
  'deposit': 3820.0,
  'final': 0.0},
 {'who': 'Stone',
  'person': None,
  'trade': '',
  'what': 'Stone',
  'agreed': 3500.0,
  'deposit': 0.0,
  'final': 3500.0},
 {'who': 'Un accounted for money',
  'person': None,
  'trade': '',
  'what': '1550 can not be accounted for',
  'agreed': 1550.0,
  'deposit': 0.0,
  'final': 1550.0},
 {'who': 'Mastic Guy',
  'person': 'The mastic guy',
  'trade': 'paint and mastic',
  'what': 'One plastic + Transport',
  'agreed': 500.0,
  'deposit': 0.0,
  'final': 500.0}]

db = sqlite3.connect(DB)
c = db.cursor()

c.execute("SELECT id FROM ventures WHERE name = 'Phase 1'")
r = c.fetchone()
if not r:
    print("No Phase 1 under the Freetown house - make it first."); sys.exit(1)
PHASE1 = r[0]

c.execute("SELECT COUNT(*) FROM ledger_entries WHERE venture_id = ?", (PHASE1,))
if c.fetchone()[0]:
    print("Phase 1 already has lines on it. Nothing done - clear it first if "
          "you meant to run this again."); sys.exit(1)

# the people, matched to anyone already in the book
def person_id(name, trade):
    c.execute("SELECT id FROM ledger_people WHERE LOWER(name) = LOWER(?)", (name,))
    got = c.fetchone()
    if got:
        return got[0]
    c.execute("""INSERT INTO ledger_people (name, what_they_do, active)
                 VALUES (?, ?, 1)""", (name, trade))
    return c.lastrowid

def add(pid, kind, amount, note, who_owes='them'):
    if amount <= 0:
        return 0
    c.execute("""INSERT INTO ledger_entries (person_id, venture_id, kind, who_owes,
                 amount, currency, note, happened_on)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
              (pid, PHASE1, kind, who_owes, amount, CUR, note[:160], WHEN))
    return 1

made = {"people": 0, "agreed": 0, "paid": 0, "things": 0}
seen = {}
for row in ROWS:
    pid = None
    if row["person"]:
        if row["person"] not in seen:
            seen[row["person"]] = person_id(row["person"], row["trade"])
            made["people"] += 1
        pid = seen[row["person"]]
    else:
        made["things"] += 1
    note = row["what"] if row["what"] else row["who"]
    if not row["person"] and row["who"].lower() not in note.lower():
        note = row["who"] + " - " + note
    made["agreed"] += add(pid, "agreed", row["agreed"], note)
    made["paid"] += add(pid, "paid", row["deposit"], note + " (deposit)")
    made["paid"] += add(pid, "paid", row["final"], note + " (final payment)")

db.commit()

# read it back and check it against the sheet
c.execute("""SELECT COALESCE(SUM(CASE WHEN kind='agreed' THEN amount END),0),
                    COALESCE(SUM(CASE WHEN kind='paid' THEN amount END),0)
             FROM ledger_entries WHERE venture_id = ?""", (PHASE1,))
agreed, paid = c.fetchone()
db.close()

print("Phase 1 is in.")
print("  " + str(made["people"]) + " people, " + str(made["things"]) + " things to buy")
print("  " + str(made["agreed"]) + " agreements, " + str(made["paid"]) + " payments")
print("")
print("  agreed     {:>12,.0f}   the sheet says 649,860".format(agreed))
print("  paid       {:>12,.0f}   the sheet says 578,760".format(paid))
print("  still owed {:>12,.0f}   the sheet says  71,100".format(agreed - paid))
if round(agreed) == 649860 and round(paid) == 578760:
    print("")
    print("  Matches the spreadsheet to the leone.")
